name: Unit Test and Coverage

on:
  push:
    branches:
      - dev

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - run: npm ci

      - run: npm run test:cov
